<h2>Usuários</h2>

<div ng-controller="MainController">

<form class="form-inline" action="<?php echo PATH?>usuario/cadastrar" style="width:1000px; margin:auto" method="post">
	<div class="form-group">
    <label for="nome">Nome: </label>
    <input type="text" class="form-control" id="nome" name="nome" value="<?php echo $view_usuario[0]['nome']?>" required>
  </div>	
  <div class="form-group">
    <label for="email">Email: </label>
    <input type="email" class="form-control" id="email" name="email" value="<?php echo $view_usuario[0]['email']?>" required>
  </div>
  <div class="form-group">
    <label for="senha">Senha: </label>
    <input type="password" class="form-control" id="senha" name="senha" value="<?php echo $view_usuario[0]['senha']?>" required>
  </div>
  <?php
  if($view_editar){
  ?>
  <input type="hidden" name="user_id" value="<?php echo $view_editar?>">
  <?php }?>
  <input type="submit" name="Submit" value="<?php echo ($view_editar?"Alterar":"Cadastrar")?>" class="btn btn-<?php echo ($view_editar?"primary":"default")?>">
</form>
<br>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>ID</th>
			<th>Nome</th>
			<th>Email</th>
			<th style="width:200px"></th>
		</tr>
	</thead>
	<tbody>
	
	<tr ng-repeat="user in users">
		<td id="user_{{ user.user_id }}">{{ user.user_id }}</td>
		<td>{{ user.nome }}</td>
		<td>{{ user.email }}</td>
		<td>			
			<button class="btn btn-success" ng-click="Editar(user.user_id)">Editar</button>
			<button class="btn btn-danger" ng-click="Excluir(user.user_id)">Excluir</button>
		</td>
	</tr>

	</tbody>
</table>

</div>